# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'webViewJsHtml' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for webViewJsHtml

  target 'webViewJsHtmlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'webViewJsHtmlUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'GRMustache'
end
